### PR TITLE
MacOS app crashes multiple times

### LINKED ISSUE #151: MacOS app crashes multiple times
While testing the MacOS app, I noticed that the app crashes a lot. Mostly when I cancel downloading the profiles

### PR DESCRIPTION
**Pull request by risinggalaxy**
Fixes #151

### CODE REVIEW

File: geteduroam/GeteduroamPackage/Sources/Main/CustomExternalUserAgent.swift
Comment (johankool) [inline geteduroam/GeteduroamPackage/Sources/Main/CustomExternalUserAgent.swift:1]: Move to AuthClient

File: geteduroam/GeteduroamPackage/Sources/Main/CustomExternalUserAgent.swift [hunk 1]
```diff
@@ -0,0 +1,81 @@
+//
+//  CustomExternalUserAgent.swift
+//  GeteduroamPackage
+//
+//  Created by Yasser Farahi on 05/12/2024.
+//
+
+
```
Comment (johankool) [inline geteduroam/GeteduroamPackage/Sources/Main/CustomExternalUserAgent.swift:8]: Default headers can be left out.

**Review by johankool — CHANGES_REQUESTED** [review]
On the main branch I don't get this error:

Screenshot 2024-12-09 at 11 36 41

but I get further along this error:
Screenshot 2024-12-09 at 11 40 34

**Review by johankool — APPROVED** [review]
